### ISSUE TITLE
@KirK1b 4 лаба - начальная версия

### ISSUE THREAD

**Issue by Fedor-Z** [Fedor-Z/20ITS#1]
@KirK1b, посмотрел Вашу лабу.
Что надо переделать:
1.	Процедура ввода числа. Вы что-то сами себя перехитрили. У Вас первые 60 строк идет здоровый код, который сначала вводит строку, потом делает ее разбор – и все ради того, чтобы в binary получить десятичное (заметьте, именно пока десятичное) введенное число. Не проще ввести через scanf в какую-нибудь интовую переменную, а потом скопировать значение в unsigned char переменную ? 
2.	Разбор числа на отдельные биты в массиве – штука неэффективная. Но заданию соответствует. Проверьте только, что у Вас двоичное число на экран печатается в правильном порядке, а не задом наперед.
3.	Поскольку хранение битов в массиве, как у Вас – штука крайне неэффективная (медленная) – я попрошу Вас сделать хотя бы одно задание через маски (как я показывал). Давайте сделаем это для bitrate.
4.	Не очень понятно что делают функции func и func2. Дайте им понятные названия, пожалуйста (имя функции должно отвечать на вопрос «что делает») и/или напишите коротенький комментарий.
5.	Цикл while (check != 8) { замените на for. У Вас там во всех ветках кода стоит check++ - проще это вытащить в сам for. Ну и само имя переменной check тут не к месту ( в этом конкретном цикле). Это может быть index, bitNum, просто i в конце концов. Но имя check (проверка) тут не подходит.

**Comment by KirK1b** [comment]
Обновил код пару дней назад, не могу загрузить в репозиторий так как "tip of your current branch is behind its remote counterpart". 
Git pull не решил проблему.
Код ошибки: git did not exit cleanly (exit code 1)
Необходимо сделать git revert для решения проблемы?
(в случае revert я не знаю что будет с уже удаленной мною из главного каталога Lab_work_4, потому не хотел бы делать это без необходимости)
Лог KirK1b/Lab_work_4 прикреплен.
![2021-03-12 153914](https://user-images.githubusercontent.com/79631549/110941315-32056e00-8349-11eb-96f0-8e71e4761471.png)

**Comment by Fedor-Z** [comment]
Git pull как раз должен решить эту проблему. Он у Вас просто не отработал до конца - на это указывает код ошибки. 
Ппробуйте с включенным и выключенным rebase after fetch в диалоге пулла. Если оба не работают - пришлите мне логи на почту, будем разбираться. git revert не делайте - это отмена ваших последних (или не последних) изменений.

**Comment by Fedor-Z** [comment]
Логи - я имею в виду полностью текст того, что выдает TortoiseGit  после попытки сделать pull

**Comment by KirK1b** [comment]
Rebase after fetch после git pull помог, спасибо)

**Comment by Fedor-Z** [comment]
Посмоттрел новую версию. 
Есть замечания:
1. @KirK1b 
https://github.com/Fedor-Z/20ITS/blob/1aacd62fe9e411249cb5fcd9a74096a5422e7aa3/KirK1b/Lab_Work_4/Main.cpp#L54
Вы или используйте 2 сдвига, или используйте маски. Такой комбинированный вариант смысла не имеет, т.к. сдвиг влево здесь совсем не нужен (если бы не было маски, то он бы имел смысл, но тут все ненужные биты занулит маска). Исправьте во всех местах, пожалуйста.
2. https://github.com/Fedor-Z/20ITS/blob/1aacd62fe9e411249cb5fcd9a74096a5422e7aa3/KirK1b/Lab_Work_4/Main.cpp#L99
Нет смысла в If-ах - там внутри одинаковый код
3. https://github.com/Fedor-Z/20ITS/blob/1aacd62fe9e411249cb5fcd9a74096a5422e7aa3/KirK1b/Lab_Work_4/Main.cpp#L98
А почему count = binary ? В чем смысл ? Ниже по коду туда другое значение пишется.
4. Неправильное условие:
https://github.com/Fedor-Z/20ITS/blob/1aacd62fe9e411249cb5fcd9a74096a5422e7aa3/KirK1b/Lab_Work_4/Main.cpp#L115
Есть 2 способа проверки CS - выбирайте любой. Первый, сравнить расчетную CS (count) с тем, что хранится в сохраненной CS (в бите 0). Второй вариант - когда считаете CS добавить к расчетным битам еще и бит с сохраненной CS (т.е. считать биты не от 1 до 4, а от 0 до 4). Если получился 0 - то все ок, если 1 - то значит суммы не совпали. Посмотрите формулы, там можно это доказать чисто математически.
Пожалуйста, потестируйте программу с разными числами и проверьте, что проверка CS работает корректно. У вас число печатается в двоичном виде, а значит можете вручную легко подсчитать контрольную сумму по нескольким битам.

**Comment by Fedor-Z** [comment]
Работа принята. Интересная у Вас формула получилась для вычисления битрейта, хоть и сложная, но компактнее большого свитча.
Небольшие замечания (править не нужно, но примите к сведению на будущее):
1. for (int e = 0; e < 8; e++) {
			if (transl == e) {
Здесь for не нужен вообще. У вас же тело цикла будет работать только если transl==e, а значит во все формулы надо подставлять transl вместо e и убрать цикл и if
2. Не стесняйтесь использовать дополнительные переменные если нужно. У Вас везде используется transl, и для хранения копии исходного числа, и для вычисленных результатов. Я бы писал что-то вроде:
int mode;
mode = (bitrate >> 7) & 1;
избыток переменных, впрочем, тоже зло, надо соблюдать баланс. Но точно не стоит использовать одну и ту же переменную в разных по смыслу выражениях - ее имя должно соответствовать смыслу хранимого значения.
