### ISSUE TITLE
@DmitrySuvorov Вопрос по переводу чисел

### ISSUE THREAD

**Issue by Fedor-Z** [Fedor-Z/20ITS#2]
https://github.com/Fedor-Z/20ITS/blob/c6124cde577ebd07bc37fb1f02b043b8cd9ea508/Suvorov/Dmitry%20Suvorov%20Lab%204/Dmitry%20Suvorov%20Lab%204/Dmitry%20Suvorov%20Lab%204.cpp#L8

В этой функции интересный алгоритм перевода в двоичную форму. Поясните его работу на примере, пожалуйста, например если я ввел число 165 ? Можно прямо ответом здесь.

**Comment by Fedor-Z** [comment]
Да, в остальном работа хорошо сделана, жду контрольную сумму.

**Comment by DmitrySuvorov** [comment]
Извините, ранее не увидел вашего сообщения. Этот модуль представляет собой метод сравнения. Если к примеру ваше число 165 больше заданного мною числа step 128, то он выполняет вычитание, совмещённое с присваиванием, то есть из 165 вычитает 128. Остается 37. После этого в этом шаге заданный step сокращается вдвое, и в следующем снова сравнивается с числом, оставшимся после выполнения предыдущего шага. Таким образом реализуется метод больше/меньше, который собственно и пишет 1, в случае если значение последующего шага больше последующего сокращения step (0 - если не выполнено условие какое то число x>=step). Брал честно из какой то книги, которая валялась у отца в гараже(их там достаточно много). Там похожий метод я увидел с переводом 10-ти значного числа в 16-ную систему, и подогнал под двоичный метод.

**Comment by DmitrySuvorov** [comment]
В этом методе просто идёт замена обычного деления на 2 на вычитание с половинным сокращением шага.
Просто этот метод показался мне самым верным, так как тут идёт не просто остаток от деления на 2, а для си поставлено условие сравнения, если даже числа доходят практически до 0( там если ограничение по i до 8 знаков убрать, и поставить к примеру 25, то у числа 55 он дальше его 8-ми битного кода будет писать одни единицы)

**Comment by Fedor-Z** [comment]
Дмитрий, объяснение вроде есть, но оно не четкое
Поясните на примере. Возьмем число 165. В двоичном виде это 10100101
Вот покажите что происходит на каждой итерации цикла, в виде:
dec=тому-то, step = тому-то, вычитаем (или нет), теперь dec=тому-то. Печатаем 1 (или 0)
И так 8 строчек (у Вас же цикл на 8 итераций) ?

И второй еще вопрос возник - что в этой функции надо поменять, чтобы она печатала не 8 двоичных разрядов, а 16 (и корректно показывала 16 двоичных бит от числа dec) ? Можете прямо измененный код сюда вставить (или написать что нужно поменять)

**Comment by DmitrySuvorov** [comment]
Берем 165. Оно прогоняется в функции с условием больше или меньше заданного числа step=128. Первый шаг: 165 больше 128, поэтому на экран пишется 1, вместо числа 165 в ячейку dec записывается разность между dec и step. То есть будет 165-128=37. Сравниваемое число step сокращается вдвое и алгоритм идёт по новой. Наше оставшееся число 37 сравнивается с новым числом step=128/2=64. Так как оно меньше, пишется 0. На этом шаге никаких преобразований с dec происходить не будет, только step сократиться снова вдвое. Третий шаг, снова сравнение: 37>32, следовательно, на экран выводится 1, к dec присваивается 37-32=5, step сокращается вдвое. Последующие 2 шага: 5<32, печатается 0, 5<16, снова печатается 0. 
А вот уже с третьим тут почему то если вручную считать, то будет 5<8, то есть 0, а должна быть 1. Вы это имели ввиду, вас это смутило?
Но если продолжить алгоритм: 5>4, 1; 1<2, 0; 1=1, 1. То есть он куда то в никуда девает один 0. Хм, странно

А чтобы она печатала 16 знаков, и при этом правильно, нужно значение step задать максимальное для int, то есть step=32768, ну а i<=16

то есть вот так
void dvoichsyst(int dec)
{
	int step;
	step = 32768;
	printf("Binary code of a number: ");
	for (int i = 1; i <= 16; i++)
	{
		if (dec >= step)
		{
			printf("1");
			dec -= step;
		}
		else
			printf("0");

		step /= 2;
	}
	printf("\n");
}

В общем вы хотели сказать, что вот этот 0 просто испаряется в никуда, и мой метод не особо подходит?:)

**Comment by Fedor-Z** [comment]
Ну вы на самом деле ошиблись в рассуждениях немного, хотя в алгоритме вроде разобрались. На 3 шаге забыли 32 на 2 поделить и на 4 шаге используется опять 32. В остальном все верно, вопрос закрыт. Жду финальный код лабы.
