### ISSUE TITLE
Лаба 4: финальные правки+ доп. задание

### ISSUE THREAD

**Issue by Fedor-Z** [Fedor-Z/20ITS#3]
Остались последние мелочи:
1.
https://github.com/Fedor-Z/20ITS/blob/1aacd62fe9e411249cb5fcd9a74096a5422e7aa3/Makh/Laba%204/Laba%204/Laba%204.cpp#L25
Вот в этих 3 строчках (25-27) есть лишние сдвиги, уберите их, пожалуйста.

2. Вместо суммирования и взятия последнего бита можно просто использовать операцию ^ при вычислении суммы бит (т.е. суммировать по модулю 2 - это и есть операция ^ ) Так будет быстрее, исправьте пожалуйста.
3.  Доп. задание - в рассчете контрольно суммы вместо суммирования прямого суммирования бит в одну строчку, напишите код котрый будет это делать через цикл (т.к. для большого числа бит это будет правильное универсальное решение). Можно прямо в коде, можно здесь в ответе.

**Comment by Siked01** [comment]
Если что, я доделанную версию скинул
